name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@v5
      - run: lua -e "assert(loadfile('nvoip.lua'))"
      - run: for file in examples/*.lua; do lua -e "assert(loadfile('$file'))"; done
